// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoCUwfFk10Qem6yYetEvWS5TEpBL2UtaI',
    appId: '1:480600178652:ios:368412adfa8b8830f01919',
    messagingSenderId: '480600178652',
    projectId: 'sportquality-b6b25',
    storageBucket: 'sportquality-b6b25.firebasestorage.app',
    iosClientId: '480600178652-4i486lbg0tbujsur051bd5j91i6ajubb.apps.googleusercontent.com',
    iosBundleId: 'com.example.pedidos',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoCUwfFk10Qem6yYetEvWS5TEpBL2UtaI',
    appId: '1:480600178652:ios:368412adfa8b8830f01919',
    messagingSenderId: '480600178652',
    projectId: 'sportquality-b6b25',
    storageBucket: 'sportquality-b6b25.firebasestorage.app',
    iosClientId: '480600178652-4i486lbg0tbujsur051bd5j91i6ajubb.apps.googleusercontent.com',
    iosBundleId: 'com.example.pedidos',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUKeVEcArJ2rX7yWDySG2m5w3dS4ogNw8',
    appId: '1:480600178652:web:cd91729ec2bb4800f01919',
    messagingSenderId: '480600178652',
    projectId: 'sportquality-b6b25',
    authDomain: 'sportquality-b6b25.firebaseapp.com',
    storageBucket: 'sportquality-b6b25.firebasestorage.app',
    measurementId: 'G-94NP3B748M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmbIh0rv-XOCpGUhSTGwl_TQZVJY3imqM',
    appId: '1:480600178652:android:1ba64fbd52f65b7df01919',
    messagingSenderId: '480600178652',
    projectId: 'sportquality-b6b25',
    storageBucket: 'sportquality-b6b25.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDERep57BhQBwwvfcIIK4htN8EZCkptnU4',
    appId: '1:480600178652:web:0d9f53b70c162c3af01919',
    messagingSenderId: '480600178652',
    projectId: 'sportquality-b6b25',
    authDomain: 'sportquality-b6b25.firebaseapp.com',
    storageBucket: 'sportquality-b6b25.firebasestorage.app',
    measurementId: 'G-EPZL5K5FRE',
  );
}
